#!/bin/bash
nvchecker source.ini
awk '{print $1}' < new_ver.txt | xargs -i sh -c "mkdir {} && git -C {} init && git -C {} remote add origin git+ssh://aur@aur.archlinux.org/{}.git && git -C {} config core.sshCommand 'ssh -i ../.ssh/id_rsa'"
